#ifndef PERMISSOES_H
#define PERMISSOES_H

#include <QDialog>
#include <QDebug>
#include <QtSql>
#include <QMessageBox>
namespace Ui {
class permissoes;
}

class permissoes : public QDialog
{
    Q_OBJECT

public:
    explicit permissoes(QWidget *parent = nullptr, QString clicou = "");
    ~permissoes();

private slots:
    void on_cancelar_clicked();

    void on_Aplicar_clicked();

    QString BoolToString(bool b);

private:
    QSqlQuery query;
    Ui::permissoes *ui;
    QString tipo;
    QString grupo;
    QString alterarsenha;
    QString consultapermissoes;
    QString inserepermissoes;
    QString editapermissoes;
    QString visualizapermissoes;
    QString excluipermissoes;
    QString relatoriopermissoes;
    QString consultapessoal;
    QString inserepessoal;
    QString editapessoal;
    QString visualizapessoal;
    QString excluipessoal;
    QString relatoriopessoal;
    QString consultasetor;
    QString inseresetor;
    QString editasetor;
    QString visualizasetor;
    QString excluisetor;
    QString relatoriosetor;
    QString consultauf;
    QString insereuf;
    QString editauf;
    QString visualizauf;
    QString excluiuf;
    QString relatoriouf;
    QString consultamunicipio;
    QString inseremunicipio;
    QString editamunicipio;
    QString visualizamunicipio;
    QString excluimunicipio;
    QString relatoriomunicipio;
    QString consultacep;
    QString inserecep;
    QString editacep;
    QString visualizacep;
    QString excluicep;
    QString relatoriocep;
    QString consultafabricante;
    QString inserefabricante;
    QString editafabricante;
    QString visualizafabricante;
    QString excluifabricante;
    QString relatoriofabricante;
    QString consultafornecedor;
    QString inserefornecedor;
    QString editafornecedor;
    QString visualizafornecedor;
    QString excluifornecedor;
    QString relatoriofornecedor;
    QString consultaproduto;
    QString insereproduto;
    QString editaproduto;
    QString visualizaproduto;
    QString excluiproduto;
    QString relatorioproduto;
    QString consultatipoproduto;
    QString inseretipoproduto;
    QString editatipoproduto;
    QString visualizatipoproduto;
    QString excluitipoproduto;
    QString relatoriotipoproduto;
    QString consultaapresentacao;
    QString insereapresentacao;
    QString editaapresentacao;
    QString visualizaapresentacao;
    QString excluiapresentacao;
    QString relatorioapresentacao;
    QString consultaformafarmaceutica;
    QString insereformafarmaceutica;
    QString editaformafarmaceutica;
    QString visualizaformafarmaceutica;
    QString excluiformafarmaceutica;
    QString relatorioformafarmaceutica;
    QString consultaclassificacaoterapeutica;
    QString insereclassificacaoterapeutica;
    QString editaclassificacaoterapeutica;
    QString visualizaclassificacaoterapeutica;
    QString excluiclassificacaoterapeutica;
    QString relatorioclassificacaoterapeutica;
    QString consultaprincipioativo;
    QString insereprincipioativo;
    QString editaprincipioativo;
    QString visualizaprincipioativo;
    QString excluiprincipioativo;
    QString relatorioprincipioativo;
    QString consultaunidadeconcentracao;
    QString insereunidadeconcentracao;
    QString editaunidadeconcentracao;
    QString visualizaunidadeconcentracao;
    QString excluiunidadeconcentracao;
    QString relatoriounidadeconcentracao;
    QString consultaprodutoprincipioativo;
    QString insereprodutoprincipioativo;
    QString editaprodutoprincipioativo;
    QString visualizaprodutoprincipioativo;
    QString excluiprodutoprincipioativo;
    QString relatorioprodutoprincipioativo;
    QString consultapaintpa;
    QString inserepaintpa;
    QString editapaintpa;
    QString visualizapaintpa;
    QString excluipaintpa;
    QString relatoriopaintpa;
    QString consultainteracao;
    QString insereinteracao;
    QString editainteracao;
    QString visualizainteracao;
    QString excluiinteracao;
    QString relatoriointeracao;
    QString consultabibliografia;
    QString inserebibliografia;
    QString editabibliografia;
    QString visualizabibliografia;
    QString excluibibliografia;
    QString relatoriobibliografia;
    QString consultaestoqueminimo;
    QString insereestoqueminimo;
    QString editaestoqueminimo;
    QString visualizaestoqueminimo;
    QString excluiestoqueminimo;
    QString relatorioestoqueminimo;
    QString consultamodalidadecompra;
    QString inseremodalidadecompra;
    QString editamodalidadecompra;
    QString visualizamodalidadecompra;
    QString excluimodalidadecompra;
    QString relatoriomodalidadecompra;
    QString consultaalergias;
    QString inserealergias;
    QString editaalergias;
    QString visualizaalergias;
    QString excluialergias;
    QString relatorioalergias;
    QString consultacid10;
    QString inserecid10;
    QString editacid10;
    QString visualizacid10;
    QString excluicid10;
    QString relatoriocid10;
    QString consultarequisicao;
    QString insererequisicao;
    QString editarequisicao;
    QString visualizarequisicao;
    QString excluirequisicao;
    QString relatoriorequisicao;
    QString consultaatendimentorequisicao;
    QString insereatendimentorequisicao;
    QString editaatendimentorequisicao;
    QString visualizaatendimentorequisicao;
    QString excluiatendimentorequisicao;
    QString relatorioatendimentorequisicao;
    QString consultaentradamaterial;
    QString insereentradamaterial;
    QString editaentradamaterial;
    QString visualizaentradamaterial;
    QString excluientradamaterial;
    QString relatorioentradamaterial;
    QString consultaentradanf;
    QString insereentradanf;
    QString editaentradanf;
    QString visualizaentradanf;
    QString excluientradanf;
    QString relatorioentradanf;
    QString consultaestoque;
    QString insereestoque;
    QString editaestoque;
    QString visualizaestoque;
    QString excluiestoque;
    QString relatorioestoque;
    QString consultaajusteestoque;
    QString insereajusteestoque;
    QString editaajusteestoque;
    QString visualizaajusteestoque;
    QString excluiajusteestoque;
    QString relatorioajusteestoque;
    QString consultapaciente;
    QString inserepaciente;
    QString editapaciente;
    QString visualizapaciente;
    QString excluipaciente;
    QString relatoriopaciente;
    QString consultacontroleprescricao;
    QString inserecontroleprescricao;
    QString editacontroleprescricao;
    QString visualizacontroleprescricao;
    QString excluicontroleprescricao;
    QString relatoriocontroleprescricao;
    QString consultamotivo;
    QString inseremotivo;
    QString editamotivo;
    QString visualizamotivo;
    QString excluimotivo;
    QString relatoriomotivo;
    QString consultaatendimentoprescricao;
    QString insereatendimentoprescricao;
    QString editaatendimentoprescricao;
    QString visualizaatendimentoprescricao;
    QString excluiatendimentoprescricao;
    QString relatorioatendimentoprescricao;
    QString internacao_alta;
    QString notificaprescricao;
    QString logsistema;
};

#endif // PERMISSOES_H
